version: "2.4"
services:
  minio:
    image: minio/minio:latest
    container_name: ecci_minio
    volumes:
      - cloud-minio-data:/data
    restart: always
    ports:
      - "${ECCI_MINIO_PORT}:9000"
    environment:
      MINIO_ACCESS_KEY: ${ECCI_MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${ECCI_MINIO_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  ecci_file_manager:
    image: registry.gitlab.com/wangluhui/edgeai/file-manager:latest
    container_name: ecci_file_manager
    env_file: .env
    restart: always
    depends_on:
      - minio

volumes:
  cloud-minio-data:
