version: "2.4"
services:
  agent:
    image: registry.gitlab.com/wangluhui/edgeai/agent:latest
    container_name: ecci_agent
    env_file: .env
    # environment:
    #   ECCI_BROKER_IP: ${ECCI_BROKER_IP}
    #   ECCI_BROKER_PORT: ${ECCI_BROKER_PORT}
    #   ECCI_AGENT_ID: ${ECCI_AGENT_ID}
    #   ECCI_MQTT_CLIENT_ID: ${ECCI_MQTT_CLIENT_ID}
    #   ECCI_USERNAME: ${ECCI_USERNAME}
    #   ECCI_PASSWORD: ${ECCI_PASSWORD}
    #   ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP}
    #   ECCI_LOCAL_BROKER_PORT: ${ECCI_LOCAL_BROKER_PORT}
    #   ECCI_LOCAL_BROKER_ID: ${ECCI_LOCAL_BROKER_ID}
    #   ECCI_LOCAL_BROKER_USERNAME: ${ECCI_LOCAL_BROKER_USERNAME}
    #   ECCI_LOCAL_BROKER_PASSWORD: ${ECCI_LOCAL_BROKER_PASSWORD}
    #   ECCI_REGISTRY_URL: ${ECCI_REGISTRY_URL}
    #   ECCI_REGISTRY_USERNAME: ${ECCI_REGISTRY_USERNAME}
    #   ECCI_REGISTRY_PASSWORD: ${ECCI_REGISTRY_PASSWORD}
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/data/:/agent/data/